// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden"
	"raidendb/internal/controllers"
	"raidendb/internal/models"
	"github.com/valyala/fasthttp"
)

func RegisterRoute(server *raiden.Server) {
	server.RegisterRoute([]*raiden.Route{
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/books",
			Methods:    []string{},
			Controller: &controllers.BookController{},
			Model:      models.Books{},
		},
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/hello/{name}",
			Methods:    []string{fasthttp.MethodGet},
			Controller: &controllers.HelloWordController{},
		},
	})
}
